Document page styling
calblueprint/siren pull request #60
Opened 2022-02-28 08:56 UTC by whuang7000

# ✨ New in this PR ✨

## One liner: what did you do? 🚨 
Styled document upload page

## Coverage 🙆‍♀️
_use this section to break up your task into submodules and track progress_ 
 - [X] Page text
 - [X] Modal
 - [ ] Upload tutorial (added todo for new mem sprint task) 
 - [ ] Style buttons in the modal

## How can the reviewer test your code? 👩‍💻
Go to upload page

## Any bugs you encountered or still having trouble with? 🐛
_describe how you solved them such that someone can follow your explanation_ 

## Resources 📔
_link online resources and related PRs_ 

🧜‍♀️ cc: @shannonbonet @phoebeli23

2022-03-03 04:05 UTC, bry-gavino commented
thank you for the PR will!! I'm liking how it's looking so far, but I'm gonna go over this with Jared before merging. thanks again!

2022-03-07 01:06 UTC, j-keating0002 commented on src/screens/Upload/CameraScreen.tsx
>    LogBox,
i allowed access to all photos + camera but when trying to takes photos received error: missing camera or camera roll permissions
![image](https://user-images.githubusercontent.com/57604304/156951060-12f7d9d3-8afc-4f0a-b72c-ab48f6e211d4.png)
possible fix: https://github.com/expo/expo/issues/4826 using expo-camera package?

2022-03-07 01:27 UTC, j-keating0002 requested changes
- camera permissions error
- fixed some styling errors

2022-03-09 17:47 UTC, bry-gavino commented
> bugs:
> 
> * camera permissions error
> * selecting new photos when adding a page removes all of the previous uploaded photos
> 
> fixed:
> 
> * fixed some styling errors

Hey Jared, is this ready for merging?

2022-03-09 17:49 UTC, bry-gavino approved these changes
Hey Will! Thanks for the great implementation and styling! Can't wait to merge this and have some new mems work on those tasks you mentioned!

2022-03-10 02:21 UTC, merged